# Generated by Django 4.2.7 on 2023-11-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0005_customuser_total_time_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_sessions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='device_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_device_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_alerts',
            field=models.JSONField(default=list),
        ),
    ]
