# Generated by Django 4.2.7 on 2023-11-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0008_customuser_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
