# Generated by Django 4.2.7 on 2023-12-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0012_userrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='problem_description',
            field=models.TextField(default=''),
        ),
    ]
