# Generated by Django 4.2.7 on 2024-01-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0013_userrequest_problem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
