# Generated by Django 4.2.7 on 2023-11-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0002_customuser_is_2fa_enabled_customuser_top_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile_pic.png', null=True, upload_to='profile_pics/'),
        ),
    ]
