# Generated by Django 4.2.7 on 2023-11-20 23:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the account was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_updated_timestamp',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the account was last updated.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed_login_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last failed login attempt.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_password_change',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last password change.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_attempts',
            field=models.IntegerField(default=0, help_text='Number of failed login attempts.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_strength',
            field=models.IntegerField(default=0, help_text="Strength of the user's password."),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_question_reset_attempts',
            field=models.IntegerField(default=0, help_text='Number of failed security question reset attempts.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_question_reset_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last failed security question reset attempt.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='successful_logins',
            field=models.IntegerField(default=0, help_text='Number of successful logins.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_method',
            field=models.CharField(blank=True, help_text='Method used for Two-Factor Authentication (e.g., SMS, Email, App).', max_length=20, null=True),
        ),
    ]
