# Generated by Django 4.2.7 on 2023-11-20 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0004_customuser_account_created_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_time_spent',
            field=models.DurationField(default='0:00', help_text='Total time spent on dashboard since account creation or reset'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_created_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the account was created.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_updated_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the account was last updated.'),
        ),
    ]
