# Generated by Django 4.2.7 on 2023-12-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0009_customuser_phone_number_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_device_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
